production:
  url: <% ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: jason
  password: D1ckn0s3
